=== dot-alter/Altered-Icons/icons/.schemas/icon.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./icons/.schemas/icon.schema.json",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },
  "title": "Altered Icons Metadata Schema",
  "description": "Schema definition for icon metadata JSON files",
  "type": "object",
  "required": [
    "$schema",
    "name",
    "aliases",
    "tags",
    "categories",
    "contributors"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "description": "path for json files scheme"
    },
    "name": {
      "type": "string",
      "description": "Unique identifier (ID) for the icon"
    },
    "aliases": {
      "type": "array",
      "items": { "type": "string" },
      "description": "Variants of the main name. Alternative search name"
    },
    "tags": {
      "type": "array",
      "items": { "type": "string" },
      "description": "Keywords or topics associated with the icon"
    },
    "categories": {
      "type": "array",
      "items": { "type": "string" },
      "description": "Primary category for the icon"
    },
    "contributors": {
      "type": "array",
      "items": { "type": "string" },
      "description": "List of contributor usernames or IDs"
    }
  },
  "additionalProperties": false
}

=== dot-alter/Altered-Icons/icons/chubby/line/arrow-down-left.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "arrow-down-left",
  "aliases": [
    "share",
    "redirect",
    "reply"
  ],
  "tags": [
    "arrow",
    "direction",
    "social",
    "navigation"
  ],
  "categories": [
    "navigation",
    "communication"
  ],
  "contributors": [
    "dot-alter"
  ]
}

=== dot-alter/Altered-Icons/icons/chubby/line/message-circle-minus.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "message-circle-minus",
  "aliases": [
    "remove-message",
    "delete-chat"
  ],
  "tags": [
    "remove",
    "delete",
    "message"
  ],
  "categories": [
    "communication",
    "actions"
  ],
  "contributors": [
    "dot-alter"
  ]
}

=== dot-alter/Altered-Icons/icons/chubby/line/diamond-question-mark.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "diamond-question-mark",
  "aliases": [
    "question-diamond",
    "help-diamond"
  ],
  "tags": [
    "question",
    "help",
    "premium"
  ],
  "categories": [
    "alerts",
    "interface"
  ],
  "contributors": [
    "dot-alter"
  ]
}

=== dot-alter/Altered-Icons/icons/chubby/line/battery-off.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "battery-off",
  "aliases": [
    "battery-disabled",
    "no-power"
  ],
  "tags": [
    "battery",
    "off",
    "disabled",
    "power-off"
  ],
  "categories": [
    "devices",
    "status"
  ],
  "contributors": [
    "dot-alter"
  ]
}

=== dot-alter/Altered-Icons/icons/chubby/line/compass.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "compass.svg",
  "aliases": [
    "navigation",
    "direction"
  ],
  "tags": [
    "map",
    "travel",
    "explore"
  ],
  "categories": [
    "accessories",
    "objects",
    "navigation"
  ],
  "contributors": [
    "dot-alter"
  ]
}

=== dot-alter/Altered-Icons/icons/chubby/line/logic-gate-not.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "logic-gate-not",
  "aliases": [
    "not-gate",
    "inverter-gate"
  ],
  "tags": [
    "electronics",
    "circuit",
    "computing"
  ],
  "categories": [
    "technology",
    "programming"
  ],
  "contributors": [
    "dot-alter"
  ]
}

=== dot-alter/Altered-Icons/icons/chubby/line/finder-face.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "finder-face",
  "aliases": [
    "file-manager",
		"folder-manager",
		"mac-os"
  ],
  "tags": [
    "folders",
    "browser",
    "files",
		"brand"
  ],
  "categories": [
    "interface",
    "actions"
  ],
  "contributors": [
    "dot-alter"
  ]
}

=== dot-alter/Altered-Icons/icons/chubby/line/message-square-dot.json
{
  "$schema": "../../.schemas/icon.schema.json",
  "name": "message-square-dot",
  "aliases": [
    "dot-chat",
    "notification-message"
  ],
  "tags": [
    "notification",
    "message",
    "unread"
  ],
  "categories": [
    "communication",
    "status"
  ],
  "contributors": [
    "dot-alter"
  ]
}
